### ISSUE TITLE
Критическая записка

### ISSUE THREAD

**Issue by LuaFan2** [Titanovsky/architecture-of-ambition#1]
По моему имхо данная структура смотрится дико. Она выглядит некрасиво и все файлы слишком разбросаны. 
Первая заметка. Зачем раскидывать kernel и loader файлы от загрузчичка так далеко? Загрузчик в авторане, остальное вообще в аддоне. Не лучше в garysmod/lua или хотя-бы /garrysmod/lua/autorun их кинуть? Это же ядро неотделимое.
Вторая заметка. Имхо это слишком запутанная структура loader -> main.loader -> main.register. Все это сделать же можно гораздо проще, если сделать что-то типо легко интегрируемой в гейммод системы модулей аля:

gamemodes/your_gamemode_name/gamemode/amb_loader.lua
gamemodes/your_gamemode_name/gamemode/amb_config.lua -- Опционально

gamemodes/your_gamemode_name/gamemode/amb_core/хоть что

gamemodes/your_gamemode_name/gamemode/amb_modules/name/module.lua
gamemodes/your_gamemode_name/gamemode/amb_modules/name_2/module.lua

Где module.lua имеет такой вид

```
MODULE.Name
...
и дальше вся информация, которая необходима
```

Так все будет максимально прозрачно и доступно. Реализовать мою структуру module.lua можно, если использовать функции debug.setfenv, CompileFile и setmetatable. При необходимости могу продемонстрировать, как.

**Comment by Titanovsky** [comment]
Я думал мой гитхаб никто никогда не найдёт, а тут вот как вышло.

Она дикая да, альфа же, самая первая версия. Насчёт разбросанности, если смотреть относительно папки garrysmod загрузчик системы находится в lua/autorun, а сама система в addons/kernel. Две папки. 

1 - почему так далеко, всё очень просто. Я работаю с FTPZilla и мне просто **лень** переходить из одной папки в другую, сейчас это стало критично, так как моя мышка состарилась, и очень часто проявляется мисс клик или недоклик. Вообще, тут загрузчик (run, а не loader) - это всего лишь workaround, его то полноценным загрузчиком с трудом можно назвать, так как файлы спокойно могут и в lua, и в addons/name/lua, и в gamemodes/gamemode_name/gamemode загрузится. Почему загрузчик не в папке addons (а там вся движуха), он там был раньше, и мне показался некрасивым, я хочу, чтобы в аддонс было ядро, ассеты и обычные аддоны. Почему ядро не засунул в lua к загрузчику, всё просто, а модули и микроядро (библиотеки и защита) куда? В аддонс? Хорошо, но если loader мне нужен лишь технически, то к register.lua я обращаюсь очень часто, так как там указываются модули, какие надо подключить, какие не надо, и первичная инфа, дебаг, уровень логгирования и в будущем может что-то ещё - это всё сводится к проблеме, что мне просто **лень** переходить по папкам. Если бы можно было без run.lua обойтись, я бы обошёлся. Мне нужен только kernel. Я тут подумал, а может run.lua в к kernel запихнуть, попробую на этот счёт.
2 - Там структура L0: run.lua >> L1: kernel ( loader потом register ) >> L2: microkernel ( библиотеки и защита ) >> L3: модули. Тут может стоять вопрос, почему сначала loader, а не register - всё просто. Конфиг уже использует готовые функций, а чтобы эти функций существовали, надо сначала подгрузить loader. Ну, библиотеки раньше модулей загружаются по очевидным причина, защита тоже, потом идут модули и всё.
3 - Я работаю, если не брать во внимания run.lua, только с папкой addons, причину назвал в первом кейсе. Вообще если рассмотреть с точки зрения игры, у меня есть модуль под название gamemode, его лучше оформить, как полноценный gamemode в одноимённой папке, а сами модули складывать, как обычные аддоны в папку addons, но тогда я вернусь к обычной архитектуре, которую задумала фейспанч. Я тут снова подумал, может попробовать из addons переехать в gamemodes, точно будет правильно, потому что по сути kernel - это как глобальный гейммод в рамках игры, но будет ли это понятнее и удобнее..
4 - Я бы хотел увидеть module.lua, ни разу не работал debug.setfenv и CompileFile, было бы интересно, если можно.

**Comment by LuaFan2** [comment]
По поводу четвертого пункта.

Допустим, есть файл plugin.lua с содержимым

PLUGIN.Name = "smth"
PLUGIN.foo = "bar"

Нам, например, надо получить что-то оттуда, и чтобы выглядело эстетично.
Делаем так:

local func = CompileFile("plugin.lua")

local env = {PLUGIN = {}} -- Создаем окружение для плагина
setmetatable(env, {__index = _G}} -- делаем так, чтобы в этом окружении был доступ к обычным функциям
debug.setfenv(func, env) -- Ставим окружение для func

func() -- На этом моменте мы можем через env получать содержимое файла plugin.lua
print(env.foo) -- "bar"

**Comment by Titanovsky** [comment]
Спасибо, попробую.
