### ISSUE TITLE
ipairs vs pairs

### ISSUE THREAD

**Issue by Rorkh** [Titanovsky/architecture-of-ambition#3]
Всем цивилизованным миром признано, что ipairs работает быстрее, чем pairs. Предлагаю внести микрооптимизацию, заменить все pairs там, где это возможно без больших потерь во времени, на ipairs.
Хотя я не смотрел весь код, но как минимум одно место знаю, значит такая уязвимая точка есть.

Пруфы: https://gitspartv.github.io/LuaJIT-Benchmarks/#test10
К тому же могу легко подтвердить, что это является общепризнанным стандартом.
P.S: LuaFan2 это я(есть причины иметь 2 аккаунта)

**Comment by Titanovsky** [comment]
Когда я ещё весной прочёл этот issue, я не заметил **"где это возможно без больших потерь во времени"**. И тогда началось, я лепил просто где можно и нельзя было, в итоге где-то в мае пришёл к выводу, что ipairs всё же не волшебная таблетка, и это специфичный метод. Он нужен там, где ему больше всего благоволит ситуация. Кстати, по поводу бечмарка LuaJIT, мне понравилась идея, я раньше не занимался таким, я обязательно прочту пост и сделаю для себя выводы.

И так, с ipairs я согласен, где его можно безопасно вставить, например, player.GetAll() или ents.GetAll(), или таблицы, где изначально не указаны ключи или ключи идут по порядку, обязательно будет ipairs.
