### ISSUE TITLE
Асинхронность

### ISSUE THREAD

**Issue by Rorkh** [Titanovsky/architecture-of-ambition#4]
Предлагаю использовать данную имплементацию асинхронного стандарта для гмода с целью повышения производительности
https://github.com/brianhang/deferred-lua
Очевидно, это может использоваться не везде, но в некоторых местах может произойти ощутимый прирост.

**Comment by Titanovsky** [comment]
Совсем скоро я познакомлюсь с асинхронностью, но пока что занесу этот issue в долгий ящик. Спасибо за ссылку и за помощь в оптимизаций производительности.
