### ISSUE TITLE
unpack

### ISSUE THREAD

**Issue by Rorkh** [Titanovsky/architecture-of-ambition#5]
Заметил, что в части, отвечающей за sql и чат используется функция unpack, которая считается тяжёлой, здесь можно посмотреть на сравнение:
https://gitspartv.github.io/LuaJIT-Benchmarks/#test4

Конечно, в таких местах это не так критично, но цифры говорящие, и было бы в лучших традициях эту гадость убрать.

**Comment by Titanovsky** [comment]
На данный момент я не вижу возможности для Format(), у которого второй аргумент это varargs - [убрать unpack.](https://github.com/Titanovsky/architecture-of-ambition/blob/master/garrysmod/addons/kernel/lua/libs/sqlite/sv_sqlite.lua#L113) 

Приму к сведению про unpack и что если есть возможность не использовать его, то лучше не использовать.
